### ISSUE TITLE
NameError: name 'tf' is not defined

### ISSUE THREAD

**Issue by Sparker0i** [krasserm/face-recognition#14]
Hi, I have run your jupyter notebook file succesfully. I have then saved `nn4_small2` into a `.h5` file. I'm now trying to convert this file to tflite, for which I use the `tflite_convert` tool using the documentation [provided here](https://www.tensorflow.org/lite/convert/cmdline_examples#convert_a_tfkeras_model_) .

When I try to run this file, I get this error (note the last line, it is somewhere related to utils.py file):

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 100, in _convert_model
    converter = _get_toco_converter(flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 87, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 368, in from_keras_model_file
    keras_model = _keras.models.load_model(model_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 230, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 310, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1302, in from_config
    process_node(layer, node_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1260, in process_node
    layer(input_tensors[0], **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 739, in call
    return self.function(inputs, **arguments)
  File "/Users/sparker0i/face-recognition/utils.py", line 35, in LRN2D
    return tf.nn.lrn(x, alpha=1e-4, beta=0.75)
NameError: name 'tf' is not defined
```

In `utils.py` I can see `import tensorflow as tf` in `utils.py` but I'm still not able to deduce why this error is coming up. Could you please look into it?

**Comment by krasserm** [comment]
I got it running by defining 

```python
def LRN2D(x):
    import tensorflow as tf
    return tf.nn.lrn(x, alpha=1e-4, beta=0.75)
```

in `utils.py` i.e. did the `tf` import inside the function. That's a workaround but I hope it's fine for you.

**Comment by Sparker0i** [comment]
Thanks, I did manage to avert that error, but I have got a new one up. I don't know if this is something you could help me with.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 100, in _convert_model
    converter = _get_toco_converter(flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 87, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 368, in from_keras_model_file
    keras_model = _keras.models.load_model(model_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 219, in load_model
    f = h5py.File(filepath, mode='r')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

Were you able to convert the .h5 into .tflite?

**Comment by krasserm** [comment]
I tried `tflite_convert --output_file test.tflite --keras_model_file test.h5` and it worked i.e. created the output file.

**Comment by Sparker0i** [comment]
Okay, I did get a `.tflite` file in the end, but did you encounter an error like this during the process:

```
WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
```

**Comment by krasserm** [comment]
That's not an error but only a warning that the model was not compiled. If you only use the (converted) model for prediction you can ignore the warning.

**Comment by Sparker0i** [comment]
Oh ok. Did you encounter that?

**Comment by krasserm** [comment]
Yes

**Comment by krasserm** [comment]
Any objections to close this ticket?

**Comment by mohdshafahad** [comment]
NameError                                 Traceback (most recent call last)
<ipython-input-2-d55b98fd5a78> in <module>
----> 1 detection_graph = tf.Graph()
      2 with detection_graph.as_default():
      3   od_graph_def = tf.GraphDef()
      4   with tf.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid:
      5     serialized_graph = fid.read()

NNameError                                 Traceback (most recent call last)
<ipython-input-2-d55b98fd5a78> in <module>
----> 1 detection_graph = tf.Graph()
      2 with detection_graph.as_default():
      3   od_graph_def = tf.GraphDef()
      4   with tf.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid:
      5     serialized_graph = fid.read()

NameError: name 'tf' is not defined

**Comment by yyhhgg** [comment]
(base) C:\Users\Administrator>python
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute '__version__'
>>>
