### ISSUE TITLE
I tried `tflite_convert --output_file test.tflite --keras_model_file test.h5` and it worked i.e. created the output file.

### ISSUE THREAD

**Issue by AaradhyaSaxena** [krasserm/face-recognition#39]
I tried `tflite_convert --output_file test.tflite --keras_model_file test.h5` and it worked i.e. created the output file.

_Originally posted by @krasserm in https://github.com/krasserm/face-recognition/issues/14#issuecomment-460056922_

**Comment by AaradhyaSaxena** [comment]
I did this and got this error:

`Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/python/tflite_convert.py", line 594, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/python/tflite_convert.py", line 577, in run_main
    _convert_tf2_model(tflite_flags)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/python/tflite_convert.py", line 228, in _convert_tf2_model
    model = keras.models.load_model(flags.keras_model_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 303, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 937, in from_config
    config, custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 1893, in reconstruct_from_config
    process_layer(layer_data)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 1875, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 303, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/layers/core.py", line 947, in from_config
    config, custom_objects, 'function', 'module', 'function_type')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/layers/core.py", line 999, in _parse_function_from_config
    config[func_attr_name], globs=globs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 400, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)`

**Comment by AaradhyaSaxena** [comment]
I don't know why that did not work but this did:

import tensorflow as tf
converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file('model_fd.h5')
converter.post_training_quantize = True
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
open("quantized_model.tflite", "wb").write(tflite_model)
